### ISSUE TITLE
wifi adapter lost after change kernel

### ISSUE THREAD

**Issue by rakaprsdhkra** [navilg/rtl8723be#7]
i did everything you suggest.
in kernel 4.15.0-29-generic it worked perfectly.
however, after i update & upgrade my kernel to 4.15.0-43-generic, my wifi adaper has not found and i can't connect to any internet.
how i can fix it in my newest kernel?

**Comment by navilg** [comment]
Its better to have a configuration backup before running the script. It is sensitive to kernel versions, latest OS patches and many more things.
